{{- if .Values.createDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "frankenstein.helmlabels" . | nindent 4 }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.deploymentAnnotations }}
  annotations:
  {{ toYaml .Values.deploymentAnnotations | indent 4 }}
  {{- end }}   
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicas | default 1 }}
  selector:
    matchLabels:
    {{- include "frankenstein.helmlabels" . | nindent 6 }}     
  template:
    metadata:
      labels:
      {{- include "frankenstein.helmlabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.imageFull | default "nginx" }}
        ports:
        - name: {{ .Values.containerPortName | default "http" }}
          containerPort: {{ .Values.containerPort | default 80 }}
          protocol: TCP
{{ end }}
