{{- if .Values.createDeployment }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  {{- include "frankenstein.helmlabels" . | nindent 4 }}
  {{- if .Values.extraLabels }}
  {{- toYaml .Values.extraLabels | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.hpaMinReplicaCount | default 1 }}
  selector:
    matchLabels:
    {{- include "frankenstein.helmlabels" . | nindent 6 }}     
    {{- if .Values.extraLabels }}
    {{- toYaml .Values.extraLabels | nindent 6 }}
    {{- end }}
  template:
    metadata:
      labels:
      {{- include "frankenstein.helmlabels" . | nindent 8 }}
      {{- if .Values.extraLabels }}
      {{- toYaml .Values.extraLabels | nindent 8 }}
      {{- end }}
    spec:
      containers:
      - name: {{ .Release.Name }}
        image: {{ .Values.image | default "nginx" }}
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
        ports:
        - name: {{ .Values.containerPortName | default "http" }}
          containerPort: {{ .Values.containerPort | default 80 }}
          protocol: TCP
{{ end }}
