{{- range $secret, $values := .Values.externalSecret }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: "{{ $secret }}-{{ $.Release.Name }}"
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "frankenstein.helmlabels" $ | nindent 4 }}
    {{- if $.Values.extraLabels }}
    {{- toYaml $.Values.extraLabels | nindent 4 }}
    {{- end }}
spec:
  refreshInterval: 60s
  secretStoreRef:
    name: eso-css-default 
    kind: ClusterSecretStore
  target:
    name: {{ $secret }}
{{ toYaml $values | trim | indent 2 }}    
{{- end }}
