{{- if .Values.ingressHost }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name  }}-ingress
  annotations:
  {{- if .Values.ingressAnnotations }}
  {{- toYaml .Values.ingressAnnotations | nindent 4 }}
  {{- end }}
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: {{ .Values.ingressClassName | default "ingress-nginx" }}
  rules:
    - host: {{ .Values.ingressHost }}
      http:
        {{- if .Values.ingressPaths }}
        {{- toYaml .Values.ingressPaths | nindent 8 }}
        {{- else }}        
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name  }}
                port:
                  number: {{ .Values.containerPort | default 80 }}
        {{- end }}
{{ end }}
