name: Render Helmchart 

on:
  push:
    branches:
      - main

jobs:
  render:
    runs-on: ["self-hosted","Linux","ARM64","runner-devops"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Setup git
        run: |
               git config --global user.email "bot@doliveiraorg.com"
               git config --global user.name "bot doliveiraorg"
      - name: Update chart
        run: |
              DATE=$(date)
              mkdir -p temp/helm-frankenstein
              cp -pr *.yaml  templates/ temp/helm-frankenstein
              helm package temp/helm-frankenstein --destination repo/
              helm repo index repo/
              rm -rf temp/
              git add .
              git commit -m "new helm version $DATE"
              git push origin main


